pub mod frontend;
pub mod compression;
pub mod conversions;
pub mod encryption;
pub mod errors;
pub mod metadatas;
pub mod parameters;
pub mod treatment;
pub mod types;
pub mod context;
pub mod parallelism;
pub mod key;
use crate::types::Version;
pub const VERSION: Version = 2;
